 # 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        # jess/imagemin:latest jc21/nginx-proxy-manager
        # docker pull vaultwarden/server:1.32.5
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/vaultwarden/server:1.32.5 docker://sunlightas.asuscomm.com:4888/mirror/vaultwarden_server:1.32.5
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/jenkins/jenkins:latest docker://sunlightas.asuscomm.com:4888/mirror/jenkins:latest
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/node:lts-alpine docker://sunlightas.asuscomm.com:4888/mirror/node:lts-alpine
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/mysql:8.4.2 docker://sunlightas.asuscomm.com:4888/mirror/mysql:8.4.2
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/redis:latest docker://sunlightas.asuscomm.com:4888/mirror/redis:latest
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/jc21/nginx-proxy-manager:latest docker://sunlightas.asuscomm.com:4888/mirror/nginx-proxy-manager:latest
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/nginx:latest docker://sunlightas.asuscomm.com:4888/mirror/nginx:latest
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/jess/imagemin:latest docker://sunlightas.asuscomm.com:4888/mirror/imagemin:latest
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/gitlab/gitlab-ce:17.2.9-ce.0 docker://sunlightas.asuscomm.com:4888/mirror/gitlab-ce:17.2.9-ce.0
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/jc21/registry-ui:2.0.2 docker://sunlightas.asuscomm.com:4888/mirror/registry-ui:2.0.2
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/gitlab/gitlab-ce:16.3.9-ce.0 docker://sunlightas.asuscomm.com:4888/mirror/gitlab-ce:16.3.9-ce.0
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/gitlab/gitlab-ce:16.7.10-ce.0 docker://sunlightas.asuscomm.com:4888/mirror/gitlab-ce:16.7.10-ce.0
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/gitlab/gitlab-ce:16.11.10-ce.0 docker://sunlightas.asuscomm.com:4888/mirror/gitlab-ce:16.11.10-ce.0
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/gitlab/gitlab-ce:17.1.8-ce.0 docker://sunlightas.asuscomm.com:4888/mirror/gitlab-ce:17.1.8-ce.0
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/gitlab/gitlab-ce:17.3.7-ce.0 docker://sunlightas.asuscomm.com:4888/mirror/gitlab-ce:17.3.7-ce.0
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/gitlab/gitlab-ce:17.5.4-ce.0 docker://sunlightas.asuscomm.com:4888/mirror/gitlab-ce:17.5.4-ce.0
        skopeo copy --insecure-policy --src-tls-verify=false --dest-tls-verify=false docker://docker.io/gitlab/gitlab-ce:17.7.0-ce.0 docker://sunlightas.asuscomm.com:4888/mirror/gitlab-ce:17.7.0-ce.0
 
